[window]
opacity = 0.9
decorations_theme_variant = "dark"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 12.5

[mouse]
bindings = [
	{ mouse = "Right", action = "Paste" }
]

[keyboard]
bindings = [
	{ key = "j", mods = "Alt|Shift", action = "DecreaseFontSize" },
	{ key = "k", mods = "Alt|Shift", action = "IncreaseFontSize" },
	{ key = "c", mods = "Alt", action = "Copy" },
	{ key = "v", mods = "Alt", action = "Paste" }
]
