#!/bin/sh
xwallpaper --zoom ~/pix/wall/cache.jpg
(curl -s "https://wallhaven.cc/api/v1/search?sorting=random&atleast=1920x1080" | jq ".data[].path" | shuf -n 1 | xargs -I {} wget -O ~/pix/wall/cache.jpg {}) && xwallpaper --zoom ~/pix/wall/cache.jpg
